name: SubProj 6 HIL Mock Dashboard CI

on:
  push:
    paths:
      - 'subProj 6 HIL Mock Dashboard/**'
      - '.github/workflows/ci_subproj6.yml'
  pull_request:
    paths:
      - 'subProj 6 HIL Mock Dashboard/**'

jobs:
  test-ui:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        working-directory: './subProj 6 HIL Mock Dashboard'
        run: docker build -t subproj6_pipeline .

      - name: Run Pytest-Qt GUI Tests
        working-directory: './subProj 6 HIL Mock Dashboard'
        run: docker run --name subproj6_runner subproj6_pipeline

      - name: Extract Test Report
        if: always()
        run: |
          docker cp subproj6_runner:/app/report.html "./subProj 6 HIL Mock Dashboard/report.html"

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: pyqt5-test-report
          path: './subProj 6 HIL Mock Dashboard/report.html'
          retention-days: 30
